### ISSUE TITLE
network/networkInterface definitions fail to resolve

### ISSUE THREAD

**Issue by MikeRalphson** [Azure/azure-rest-api-specs#2176]
I've tried three resolvers on [this url](https://raw.githubusercontent.com/Azure/azure-rest-api-specs/current/specification/network/resource-manager/Microsoft.Network/2017-10-01/networkInterface.json) and they all fail to fully resolve the definition:

I believe it affects the following versions of `Microsoft.Network/*/networkInterface.json`

* 2017-06-01
* 2017-08-01
* 2017-09-01
* 2017-10-01

An example error message is:

```
#/components/schemas/NetworkInterfaceIPConfigurationPropertiesFormat/properties/subnet/%24ref
Cannot resolve reference: #/components/schemas/NetworkInterfaceIPConfigurationPropertiesFormat/properties/applicationGatewayBackendAddressPools/items/properties/properties/properties/backendIPConfigurations/items/properties/properties/properties/subnet/properties/properties/properties/routeTable/properties/properties/properties/subnets/items
```

And a `$ref` which is left unresolved is

```
./applicationGateway.json#/definitions/ApplicationGatewayBackendAddressPool
```

**Comment by MikeRalphson** [comment]
The definition is question has moved to [here](https://raw.githubusercontent.com/Azure/azure-rest-api-specs/master/specification/network/resource-manager/Microsoft.Network/stable/2017-10-01/networkInterface.json). I will retest in case the problem is fixed.

**Comment by MikeRalphson** [comment]
Errors from `sway`:

```json
{ errors: 
   [ { code: 'UNRESOLVABLE_REFERENCE',
       message: 'Reference could not be resolved: #/definitions/SubnetPropertiesFormat',
       path: [Array],
       error: 'JSON Pointer points to missing location: #/definitions/SubnetPropertiesFormat' },
     { code: 'UNRESOLVABLE_REFERENCE',
       message: 'Reference could not be resolved: #/definitions/PublicIPAddressPropertiesFormat',
       path: [Array],
       error: 'JSON Pointer points to missing location: #/definitions/PublicIPAddressPropertiesFormat' },
     { code: 'UNRESOLVABLE_REFERENCE',
       message: 'Reference could not be resolved: #/definitions/BackendAddressPoolPropertiesFormat',
       path: [Array],
       error: 'JSON Pointer points to missing location: #/definitions/BackendAddressPoolPropertiesFormat' },
     { code: 'UNRESOLVABLE_REFERENCE',
       message: 'Reference could not be resolved: #/definitions/InboundNatRulePropertiesFormat',
       path: [Array],
       error: 'JSON Pointer points to missing location: #/definitions/InboundNatRulePropertiesFormat' } ],
```

**Comment by dsgouda** [comment]
@DeepakRajendranMsft can you tag the appropriate folks from Network to take a look

**Comment by MikeRalphson** [comment]
Also https://raw.githubusercontent.com/Azure/azure-rest-api-specs/current/specification/apimanagement/resource-manager/Microsoft.ApiManagement/stable/2017-03-01/apimapis.json `#/definitions/Resource` missing.

**Comment by MarioRuiz** [comment]
This is still an issue on 2019-04-01 version.
@MikeRalphson did you manage to solve this?

**Comment by MikeRalphson** [comment]
Without a way to amend your source files, I've no way to resolve this my side.
