### ISSUE TITLE
Azure RedHat OpenShift 2022-09-04 - Internal Server Error

### ISSUE THREAD

**Issue by mbfrahry** [Azure/azure-rest-api-specs#22514]
When looking into RedHat OpenShift Cluster, we see Internal Server Error often with no additional details for what is happening. Right now I am sending the following to the API:
```
{
	"location": "westeurope",
	"name": "acctestaro230206170850589086",
	"properties": {
		"apiserverProfile": {
			"visibility": "Public"
		},
		"clusterProfile": {
			"domain": "fv3wp.com",
			"fipsValidatedModules": "Disabled",
			"pullSecret": "",
			"resourceGroupId": "/subscriptions/000-0000-0000/resourceGroups/aro-fv3wp.com"
		},
		"ingressProfiles": [{
			"name": "default",
			"visibility": "Public"
		}],
		"masterProfile": {
			"diskEncryptionSetId": "",
			"encryptionAtHost": "Disabled",
			"subnetId": "/subscriptions/000-000-000/resourceGroups/acctestRG-aro-230206170850589086/providers/Microsoft.Network/virtualNetworks/acctestvirtnet230206170850589086/subnets/main-subnet-230206170850589086",
			"vmSize": "Standard_D8s_v3"
		},
		"networkProfile": {
			"podCidr": "10.128.0.0/14",
			"serviceCidr": "172.30.0.0/16"
		},
		"servicePrincipalProfile": {
			"clientId": "XXXX",
			"clientSecret": "XXX"
		},
		"workerProfiles": [{
			"count": 3,
			"diskEncryptionSetId": "",
			"diskSizeGB": 128,
			"encryptionAtHost": "Disabled",
			"name": "worker",
			"subnetId": "/subscriptions/000-000-000resourceGroups/acctestRG-aro-230206170850589086/providers/Microsoft.Network/virtualNetworks/acctestvirtnet230206170850589086/subnets/worker-subnet-230206170850589086",
			"vmSize": "Standard_D4s_v3"
		}]
	},
	"tags": {}
}
```

This inevitably fails and returns

```
{
	"id": "/subscriptions/000-000-000/providers/microsoft.redhatopenshift/locations/westus/operationsstatus/0cb6d5f7-e249-4797-837c-50ddc338b6ad",
	"name": "0cb6d5f7-e249-4797-837c-50ddc338b6ad",
	"status": "Failed",
	"startTime": "2023-02-07T16:52:14.139187157Z",
	"endTime": "2023-02-07T17:02:17.699845524Z",
	"error": {
		"code": "InternalServerError",
		"message": "Internal server error."
	}
}
``` 

with no additional details on why it failed. Is there any way we can get more details added on why clusters are failing to create?

**Comment by navba-MSFT** [comment]
@mbfrahry Thanks for reaching out to us and reporting this issue. 

**Questions:**

- Could you please elaborate your use case ? 
- Please let me know which Azure Red Hat OpenShift Cluster API are you trying to invoke ? https://learn.microsoft.com/en-us/rest/api/openshift/open-shift-clusters?view=tfs-2017
- Please share the correlationID, Time of the issue in UTC, Subscription ID and location details over email navba [ @ ] microsoft (dot) . com. So that I can look at the backend logs for the cause of the failure.

Awaiting your reply.

**Comment by navba-MSFT** [comment]
@mbfrahry I wanted to do quick follow-up to check if you had a chance to look at my above comment. Please let us know if you had any updates on this. Awaiting your reply.

**Comment by mbfrahry** [comment]
Hey @navba-MSFT, apologies for the delay. I have emailed you

**Comment by navba-MSFT** [comment]
@mbfrahry I have emailed you my action plan to isolate this issue. Awaiting your reply.

**Comment by navba-MSFT** [comment]
@mbfrahry Thanks for your reply over email. Since you confirmed that _`The RedHat OpenShift team found the bug and should have a fix deployed by March 6th.`_ I am proceeding with closure of this issue.

**Comment by Honken77** [comment]
Hello
I am currently trying to provision a cluster with terraform azapi and keep receiving "Internal Server Error" after just 10 minutes. I am curious what the issue was that Red Hat found. Could you please share the details?

**Comment by Honken77** [comment]
> Hello I am currently trying to provision a cluster with terraform azapi and keep receiving "Internal Server Error" after just 10 minutes. I am curious what the issue was that Red Hat found. Could you please share the details?

My issue was a screw-up on my end.

**Comment by katbyte** [comment]
@navba-MSFT - the real issue here is not the one bug we encountered, but that the API is returning generic "Internal server error" messages rather then a more detailed/actionable error, as can be seen by @Honken77 encountering something similar. A proper error message likely would have helped them identify the problem quicker.

could we please reopen this issue as the real ask was for better error messages?

thanks

**Comment by mbfrahry** [comment]
Hey @navba-MSFT, I'm still seeing Internal Server Error when submitting requests. Is there a way we can reopen this issue or should I make a new one?
